name: vdt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pyyaml
  - python-dateutil
  - pytest
  - pip
  - numpy
  - pandas
  - joblib
  - scikit-learn
  - pip:
      - pymongo
      - dnspython
      - python-dotenv
      - gdown
